title: Jeremy Somsouk Bio
email: jh.somsouk@gmail.com
description: Todo todo todo todo todo todo todooooo
baseurl: ''
url: 'https://somsouk.xyz'
github_username: JeremySomsouk
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
