# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeremy Somsouk
title: Software engineer
email: jeremy@somsouk.fr
#website: https://github.com/JeremySomsouk

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  JeremySomsouk
linkedin_username: jeremy-somsouk-dev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: You're never gonna believe me
  icon: fas fa-globe
  url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About section
about_profile_image: images/profile.jpeg
about_content: |
  Hi, my name's Jeremy and I'm a software engineer. I have worked for several companies gaining teamwork and hard skills but above all, soft skills to lead projects from the ground up.

  I am most skilled in: <mark>Java</mark> and making <mark>phở</mark>

  And I am still learning how to be a <mark>great dad</mark> and that kind of leave me sleepless sometimes, but that is worth all the riches of the world.

# Main content section
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: BlaBlaCar
        link: blablacar.com
        sub_title: Software engineer
        caption: 2020 - 2024
        description: |
          Development within several teams of back-end developers for the development of the BlaBlaCar bus, carpooling inventory technical platform, and user experience. 
          - Migration of route search for different partners
          - Added discount display for bus trip details
          - Integrated the Zendesk application using our internal APIs
          - Migration and improvement of legacy PHP code bases to Java
          - Designed and implemented user experiences for drivers and user profiles
      - layout: left
        title: Streamroot Lumen
        link: streamroot.io
        sub_title: Software engineer
        caption: 2022
        description: |
          Making data services safer and easier to develop.
          - Migration of Google cloud data instances from one project to another
          - Addition of CI/CD pipelines for the data projects
      - layout: left
        title: Happn
        link: happn.com
        sub_title: Software engineer
        caption: 2017 - 2020
        description: |
          Developing within a team of 13 back-end developers for the maintenance of the happn API and the creation of new Java microservices.
          - Leading the specifications and design of new features
          - Improvements and maintenance of Java back-end microservices
          - Creation of a microservice of data storage for CRM purposes
  - title: Education
    layout: list
    content:
      - layout: left
        title: EPITA
        caption: 2012 - 2017
        sub_title: Systems, Networks and Security Engineer diploma
        #quote: >
        #  "Created 30 years ago, the EPITA computer intelligence engineering school trains those who design, develop and advance information technologies."
        description: |
          During my time at EPITA I learned the most teamwork and rigor which I try to carry on in my career. I thoroughly enjoyed my time at this school and learned how to learn fast new technologies and becoming an all around engineer.

          Even though I did a specialization in security the last two years of school, I realized quickly that my main interest was still the software engineering.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Gaming
      - Photography
      - Chess

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
