title: Jeremy Somsouk
email: jh.somsouk@gmail.com
description: Todo todo todo todo todo todo todooooo
baseurl: ''
url: 'https://somsouk.xyz'
github_username: JeremySomsouk
theme: jekyll-theme-merlot
plugins:
  - jekyll-feed
